/**
 * Defines the centralized set of error codes for the Discord bot framework.
 * 
 * Error codes are structured constants used for programmatic error handling, logging, diagnostics, and categorization of error types.
 * All codes follow the pattern: ERR_{CATEGORY}_{SPECIFIC}, allowing granular identification of issues.
 * This module groups error codes by domain, ensuring easier maintenance and clear semantic meaning across the codebase.
 * 
 * @remarks
 * - Permission-related error codes indicate authorization and context mismatches.
 * - Command-related codes reflect core command lifecycle failures.
 * - Validation codes handle argument and payload correctness.
 * - Framework codes relate to the execution environment, decorators, DI, and integration.
 * 
 * @see ErrorCode
 * @module errors/error-codes
 */

/**
 * Contains error codes associated with permission or invocation-context errors.
 * 
 * @property GUILD_ONLY - Indicates that a command is restricted to servers/guilds.
 * @property DM_ONLY - Indicates that a command is restricted to direct messages.
 * @property INSUFFICIENT_PERMISSIONS - Indicates lack of required user permissions.
 */
export const PERMISSION_ERROR_CODES = {
	GUILD_ONLY: 'ERR_PERMISSION_GUILD_ONLY',
	DM_ONLY: 'ERR_PERMISSION_DM_ONLY',
	INSUFFICIENT_PERMISSIONS: 'ERR_PERMISSION_INSUFFICIENT',
} as const;

/**
 * Contains error codes for command discovery and command execution.
 * 
 * @property NOT_FOUND - The requested command could not be found.
 * @property EXECUTION_FAILED - The command was located but failed during execution.
 * @property COOLDOWN - The command is on cooldown and cannot currently be executed.
 */
export const COMMAND_ERROR_CODES = {
	NOT_FOUND: 'ERR_COMMAND_NOT_FOUND',
	EXECUTION_FAILED: 'ERR_COMMAND_EXECUTION_FAILED',
	COOLDOWN: 'ERR_COMMAND_COOLDOWN',
} as const;

/**
 * Contains error codes pertaining to argument, option, and input validation failures.
 * 
 * @property INVALID_OPTIONS - Provided command options failed validation checks.
 * @property MISSING_REQUIRED - Required command options or arguments are missing.
 * @property OUT_OF_RANGE - Provided values are outside accepted boundaries.
 */
export const VALIDATION_ERROR_CODES = {
	INVALID_OPTIONS: 'ERR_VALIDATION_INVALID_OPTIONS',
	MISSING_REQUIRED: 'ERR_VALIDATION_MISSING_REQUIRED',
	OUT_OF_RANGE: 'ERR_VALIDATION_OUT_OF_RANGE',
} as const;

/**
 * Contains error codes for errors generated by the framework infrastructure itself.
 * 
 * @property DECORATOR_MISSING - A necessary class or method decorator is absent.
 * @property REGISTRATION_FAILED - Registration with external services (e.g., Discord API) failed.
 * @property DI_FAILED - Dependency injection process failed.
 */
export const FRAMEWORK_ERROR_CODES = {
	DECORATOR_MISSING: 'ERR_FRAMEWORK_DECORATOR_MISSING',
	REGISTRATION_FAILED: 'ERR_FRAMEWORK_REGISTRATION_FAILED',
	DI_FAILED: 'ERR_FRAMEWORK_DI_FAILED',
} as const;

/**
 * Aggregates all error codes into a unified object for typing and programmatic reference.
 */
export const ERROR_CODES = {
	...PERMISSION_ERROR_CODES,
	...COMMAND_ERROR_CODES,
	...VALIDATION_ERROR_CODES,
	...FRAMEWORK_ERROR_CODES,
} as const;

/**
 * Represents any valid error code defined in this module.
 * Used for strong typing with error classes and handlers throughout the framework.
 */
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
